name: Java 17 Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    # TODO Run multiple OS.
#    runs-on: ${{matrix.os}}
#    strategy:
#      matrix:
#        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and test timefold-solver
        run: mvn -B -Dfull verify
